#
# Copyright (c) Siemens AG, 2022
#
# Authors:
#  Cedric Hombourger <cedric.hombourger@siemens.com>
#
# This file is subject to the terms and conditions of the MIT License.
# See COPYING.MIT file in the top-level directory.
#

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ labeled ]

jobs:
  lint:
    name: Check code for issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tox
        run: |
          pip3 install --user reuse
          reuse lint
  tflite-amd64-packages:
    name: Build pycoral packages for amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build packages
        run: |
          ./kas-container build kas/meta-coral.yml
